- name: Install grafana
  yum:
    name: /tmp/grafana-9.2.0-1.x86_64.rpm
    state: latest

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://37.18.88.27:3000
    method: GET
    status_code: 200

- name: add data source prometheus
  grafana_datasource:
    name: "Prometheus"
    grafana_url: http://37.18.88.27:3000
    grafana_user: "admin"
    grafana_password: "12345"
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://37.18.88.27:9090"

- name: install node exporter dashboard
  get_url:
    url: https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
    dest: /var/lib/grafana/node-exporter.json
    mode: '0755'

- name: activate dashboard for node exporter
  template:
    src: dashboard-node-exporter.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-node-exporter.yml
    mode: 0755
  notify: restart_grafana

